# Generated by Django 3.0.11 on 2021-01-29 16:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('period', models.IntegerField()),
                ('status', models.CharField(choices=[('Not funded', 'Not funded'), ('Funded', 'Funded'), ('Completed', 'Completed')], default='Not funded', max_length=20)),
                ('paid_payments', models.IntegerField(default=0)),
                ('Borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lenme.Borrower')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Interest', models.PositiveIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('accepted', models.BooleanField(default=False)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lenme.Investor')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='lenme.Loan')),
            ],
        ),
    ]
