# Generated by Django 3.0.11 on 2021-01-29 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='email',
            field=models.EmailField(default='m@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investor',
            name='email',
            field=models.EmailField(default='a@gmail.co', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default='2012-09-04 06:00:00.000000-08:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default='2012-09-04 06:00:00.000000-08:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='investor',
            name='balance',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
