# Generated by Django 3.0.11 on 2021-01-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenme', '0003_auto_20210129_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='create_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='create_date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='loan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
