# Generated by Django 3.0.11 on 2021-01-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenme', '0004_auto_20210130_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='period',
            field=models.PositiveIntegerField(),
        ),
    ]
